update to ibc-proto 0.46, tendermint 0.37
penumbra-zone/ibc-types pull request #89
Opened 2024-06-11 23:01 UTC by dynst

This involved adding a lot of unfortunate `.unwrap()` calls that could probably be rethinked later.

Adding them isn't any worse than the status quo, I think, it just moves where the panic happens further up the stack. The [tendermint 0.36](https://github.com/informalsystems/tendermint-rs/releases/tag/v0.36.0) API change just made the edge case more obvious.

2024-06-13 22:52 UTC, conorsch commented
This is helpful, and I appreciate your submitting it, @dynst. However, we should be careful about merge timing: we're currently pinning `0.34.0` throughout the Penumbra monorepo:

https://github.com/penumbra-zone/penumbra/blob/v0.77.2/Cargo.toml#L215-L219

and we should maintain version parity on either side. A quick check on bumping the monorepo versions shows that we'd have to make fixes throughout the IBC handlers, so I'm inclined to defer this change for now.

2024-06-14 17:43 UTC, conorsch requested changes
Requesting changes simply to block premature merge: let's coordinate version bumps here with matching PRs in the monorepo. Also, the unwraps throughout may have liveness implications that we should think through carefully.

2024-06-14 18:27 UTC, dynst commented
The `.unwrap()` calls only potentially fail on chains using CometBFT 0.34, which predates the changes that ensured key and value were both valid strings. That isn't a concern for penumbra at least which is launching with cometbft 0.37.

Penumbra is using ibc-types 0.12, and 0.13.0 is the latest version, so I figured they were on different release cadences and not tightly synced, is there a reason Penumbra shouldn't just keep depending on 0.12 like it does now?

2024-11-19 17:47 UTC, erwanor commented
Thanks for getting this started @dynst, I will pick this up in a separate PR and mention you as co-author if that's alright with you.

2024-11-19 17:47 UTC, closed without merging